import type { QueryKey } from '@tanstack/react-query';
import {
  AUTH_SESSION_QUERY_KEY,
  CONTRACTS_SUMMARY_QUERY_KEY,
  DASHBOARD_SUMMARY_QUERY_KEY,
  HEALTH_ODOO_QUERY_KEY,
  MAP_AREA_GEOMETRY_QUERY_KEY,
  MAP_MANAGEMENT_DATA_QUERY_KEY,
  MAP_VIEWER_DATA_QUERY_KEY,
  MAP_ZONE_GEOMETRY_QUERY_KEY,
  buildObservationPhotosQueryKey,
  PLANTING_PHASE_OVERVIEW_QUERY_KEY,
  PLANTING_WIZARD_DATA_QUERY_KEY,
  SPECIES_PAGE_QUERY_KEY,
  TASK_MANAGEMENT_QUERY_KEY,
  USERS_PAGE_QUERY_KEY,
  buildSpeciesDetailQueryKey,
} from './query-keys';
import { invalidateQueryKeys } from './query-invalidation';

export const CREATE_TASK_INVALIDATION_QUERY_KEYS = [
  TASK_MANAGEMENT_QUERY_KEY,
  DASHBOARD_SUMMARY_QUERY_KEY,
  HEALTH_ODOO_QUERY_KEY,
] satisfies QueryKey[];

export const LOGIN_INVALIDATION_QUERY_KEYS = [
  AUTH_SESSION_QUERY_KEY,
] satisfies QueryKey[];

export const RECORD_MONITORING_RESULT_INVALIDATION_QUERY_KEYS = [
  TASK_MANAGEMENT_QUERY_KEY,
  DASHBOARD_SUMMARY_QUERY_KEY,
  CONTRACTS_SUMMARY_QUERY_KEY,
  MAP_VIEWER_DATA_QUERY_KEY,
  MAP_MANAGEMENT_DATA_QUERY_KEY,
  HEALTH_ODOO_QUERY_KEY,
] satisfies QueryKey[];

export const UPDATE_TASK_WORKFLOW_INVALIDATION_QUERY_KEYS = [
  TASK_MANAGEMENT_QUERY_KEY,
  DASHBOARD_SUMMARY_QUERY_KEY,
  HEALTH_ODOO_QUERY_KEY,
] satisfies QueryKey[];

export const UPDATE_AREA_METRICS_INVALIDATION_QUERY_KEYS = [
  MAP_MANAGEMENT_DATA_QUERY_KEY,
  MAP_VIEWER_DATA_QUERY_KEY,
  DASHBOARD_SUMMARY_QUERY_KEY,
  CONTRACTS_SUMMARY_QUERY_KEY,
] satisfies QueryKey[];

export const UPDATE_AREA_GEOMETRY_INVALIDATION_QUERY_KEYS = [
  MAP_AREA_GEOMETRY_QUERY_KEY,
  MAP_MANAGEMENT_DATA_QUERY_KEY,
  MAP_VIEWER_DATA_QUERY_KEY,
] satisfies QueryKey[];

export const CREATE_AREA_INVALIDATION_QUERY_KEYS = [
  MAP_AREA_GEOMETRY_QUERY_KEY,
  MAP_MANAGEMENT_DATA_QUERY_KEY,
  MAP_VIEWER_DATA_QUERY_KEY,
  DASHBOARD_SUMMARY_QUERY_KEY,
  CONTRACTS_SUMMARY_QUERY_KEY,
] satisfies QueryKey[];

export const UPDATE_AREA_DETAILS_INVALIDATION_QUERY_KEYS = [
  MAP_AREA_GEOMETRY_QUERY_KEY,
  MAP_MANAGEMENT_DATA_QUERY_KEY,
  MAP_VIEWER_DATA_QUERY_KEY,
  CONTRACTS_SUMMARY_QUERY_KEY,
  PLANTING_WIZARD_DATA_QUERY_KEY,
] satisfies QueryKey[];

export const DELETE_AREA_INVALIDATION_QUERY_KEYS = [
  MAP_AREA_GEOMETRY_QUERY_KEY,
  MAP_MANAGEMENT_DATA_QUERY_KEY,
  MAP_VIEWER_DATA_QUERY_KEY,
  DASHBOARD_SUMMARY_QUERY_KEY,
  CONTRACTS_SUMMARY_QUERY_KEY,
] satisfies QueryKey[];

export const UPDATE_ZONE_GEOMETRY_INVALIDATION_QUERY_KEYS = [
  MAP_ZONE_GEOMETRY_QUERY_KEY,
  MAP_MANAGEMENT_DATA_QUERY_KEY,
  MAP_VIEWER_DATA_QUERY_KEY,
] satisfies QueryKey[];

export const ADJUST_SPECIES_INVENTORY_INVALIDATION_QUERY_KEYS = [
  SPECIES_PAGE_QUERY_KEY,
] satisfies QueryKey[];

export const CREATE_SPECIES_INVALIDATION_QUERY_KEYS = [
  SPECIES_PAGE_QUERY_KEY,
  DASHBOARD_SUMMARY_QUERY_KEY,
] satisfies QueryKey[];

export function buildUpdateSpeciesInvalidationQueryKeys(speciesId: string) {
  return [
    SPECIES_PAGE_QUERY_KEY,
    buildSpeciesDetailQueryKey(speciesId),
  ] satisfies QueryKey[];
}

export const CREATE_USER_INVALIDATION_QUERY_KEYS = [
  USERS_PAGE_QUERY_KEY,
  HEALTH_ODOO_QUERY_KEY,
] satisfies QueryKey[];

export const UPDATE_USER_STATUS_INVALIDATION_QUERY_KEYS = [
  USERS_PAGE_QUERY_KEY,
  AUTH_SESSION_QUERY_KEY,
  HEALTH_ODOO_QUERY_KEY,
] satisfies QueryKey[];

export const CREATE_PLANTING_PHASE_INVALIDATION_QUERY_KEYS = [
  PLANTING_PHASE_OVERVIEW_QUERY_KEY,
  PLANTING_WIZARD_DATA_QUERY_KEY,
  DASHBOARD_SUMMARY_QUERY_KEY,
  CONTRACTS_SUMMARY_QUERY_KEY,
  MAP_VIEWER_DATA_QUERY_KEY,
  MAP_MANAGEMENT_DATA_QUERY_KEY,
] satisfies QueryKey[];

export function buildUploadObservationPhotoInvalidationQueryKeys(observationId: string | null) {
  return [
    buildObservationPhotosQueryKey(observationId),
  ] satisfies QueryKey[];
}
