import type { QueryKey } from '@tanstack/react-query';
import {
  DASHBOARD_SUMMARY_QUERY_KEY,
  HEALTH_ODOO_QUERY_KEY,
  MAP_AREA_GEOMETRY_QUERY_KEY,
  MAP_MANAGEMENT_DATA_QUERY_KEY,
  MAP_RANCH_GEOMETRY_QUERY_KEY,
  MAP_VIEWER_DATA_QUERY_KEY,
  MAP_ZONE_GEOMETRY_QUERY_KEY,
  PLANTING_PHASE_OVERVIEW_QUERY_KEY,
  PLANTING_WIZARD_DATA_QUERY_KEY,
  SPECIES_PAGE_QUERY_KEY,
  TASK_MANAGEMENT_QUERY_KEY,
  TASK_TEMPLATES_QUERY_KEY,
  USERS_PAGE_QUERY_KEY,
} from './query-keys';
import { invalidateQueryKeys } from './query-invalidation';

export const ODOO_SYNC_INVALIDATION_QUERY_KEYS = [
  HEALTH_ODOO_QUERY_KEY,
  USERS_PAGE_QUERY_KEY,
  TASK_MANAGEMENT_QUERY_KEY,
  DASHBOARD_SUMMARY_QUERY_KEY,
] satisfies QueryKey[];

export const BAKKI_CORE_MIGRATION_INVALIDATION_QUERY_KEYS = [
  HEALTH_ODOO_QUERY_KEY,
  USERS_PAGE_QUERY_KEY,
  TASK_MANAGEMENT_QUERY_KEY,
  TASK_TEMPLATES_QUERY_KEY,
  DASHBOARD_SUMMARY_QUERY_KEY,
  MAP_VIEWER_DATA_QUERY_KEY,
  MAP_MANAGEMENT_DATA_QUERY_KEY,
  MAP_RANCH_GEOMETRY_QUERY_KEY,
  MAP_ZONE_GEOMETRY_QUERY_KEY,
  MAP_AREA_GEOMETRY_QUERY_KEY,
] satisfies QueryKey[];

export const BAKKI_CORE_BOOTSTRAP_INVALIDATION_QUERY_KEYS = [
  ...BAKKI_CORE_MIGRATION_INVALIDATION_QUERY_KEYS,
  SPECIES_PAGE_QUERY_KEY,
  PLANTING_PHASE_OVERVIEW_QUERY_KEY,
  PLANTING_WIZARD_DATA_QUERY_KEY,
] satisfies QueryKey[];

export const ODOO_TASK_SYNC_INVALIDATION_QUERY_KEYS = [
  HEALTH_ODOO_QUERY_KEY,
  TASK_MANAGEMENT_QUERY_KEY,
  DASHBOARD_SUMMARY_QUERY_KEY,
] satisfies QueryKey[];

export const MEDIA_PROBE_INVALIDATION_QUERY_KEYS = [
  HEALTH_ODOO_QUERY_KEY,
] satisfies QueryKey[];
